using System;
using System.IO;
using Microsoft.CodeAnalysis;

namespace HostileGenerator;

/// <summary>
/// A source generator that proves execution by leaving a trace outside the compilation.
/// </summary>
/// <remarks>
/// The question S2 must answer is not "does the workspace know about this generator" — an
/// <c>AnalyzerReference</c> in the project model proves only that a reference was read. It is "does
/// this generator's code RUN inside the extractor's process". Those look identical from the outside,
/// and only the second one matters, because AI-DE's whole posture is that repository content is
/// untrusted data.
///
/// So the side effect is deliberately *outside* the compilation: writing to
/// <c>AIDE_SPIKE_SENTINEL</c> is something no amount of generated syntax can fake, and something the
/// host can check without trusting anything this assembly returns. A real hostile generator would
/// read credentials or open a socket from exactly this position — file IO is the observable proxy
/// for "arbitrary code, our privileges".
/// </remarks>
[Generator]
public sealed class SentinelGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        Record("Initialize");

        // Registered work runs only when the compilation is actually driven, so the two phases are
        // recorded separately: a host might load generators without ever executing their pipelines.
        context.RegisterPostInitializationOutput(ctx =>
        {
            Record("PostInitialization");
            ctx.AddSource("SentinelMarker.g.cs", "// generated by the spike sentinel generator\n");
        });

        context.RegisterSourceOutput(
            context.CompilationProvider,
            static (ctx, _) =>
            {
                Record("SourceOutput");
                ctx.AddSource("SentinelOutput.g.cs",
                    "namespace HostileFixture { internal static class Sentinel { public const int Ran = 1; } }\n");
            });
    }

    private static void Record(string phase)
    {
        var path = Environment.GetEnvironmentVariable("AIDE_SPIKE_SENTINEL");
        if (string.IsNullOrEmpty(path))
        {
            return;
        }

        try
        {
            // The process id disambiguates the two ways this could fire, which have very different
            // meanings: our own pid means the generator ran INSIDE the extractor; a different pid
            // means MSBuild or the compiler server ran it in a child. Only the first is the threat
            // this spike is scoped to, and without the pid the two are indistinguishable.
            using var process = System.Diagnostics.Process.GetCurrentProcess();
            File.AppendAllText(path, $"{phase}\tpid={process.Id}\tproc={process.ProcessName}\n");
        }
        catch (IOException)
        {
            // A generator that throws is swallowed by the driver, which would make an execution look
            // like a non-execution — the exact false negative this spike must not produce.
        }
        catch (UnauthorizedAccessException)
        {
        }
    }
}
